# Generated by Django 5.2.1 on 2025-05-10 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habit", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="periodicity",
            field=models.CharField(
                choices=[
                    ("3 days", "Каждые 3 дня"),
                    ("day", "Каждый день"),
                    ("week", "Каждую неделю"),
                    ("2 days", "Каждые 2 дня"),
                ],
                default="day",
                max_length=6,
                verbose_name="периодичность",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="related",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="related_habit",
                to="habit.habit",
                verbose_name="связанная привычка",
            ),
        ),
    ]
