# Generated by Django 5.2.1 on 2025-05-10 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habit", "0002_alter_habit_periodicity_alter_habit_related"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="periodicity",
            field=models.CharField(
                choices=[
                    ("week", "Каждую неделю"),
                    ("3 days", "Каждые 3 дня"),
                    ("2 days", "Каждые 2 дня"),
                    ("day", "Каждый день"),
                ],
                default="day",
                max_length=6,
                verbose_name="периодичность",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="time",
            field=models.TimeField(verbose_name="время начала выполнения привычки"),
        ),
    ]
